### PR TITLE
Add more metainfo to persisted data

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Each state (including sub-states) now contains the version of the corresponding package. For stdlib and builtins, the Python version (major, minor, micro) is used.

## Implementation

@adrinjalali We haven't discussed this feature in detail. Please feel open to challenge the design choices made here. 

The metainfo has just been added to the schema without a special key like "metainfo", as has been discussed previously.

Metainfo is stored on all sub-states, i.e. there is a lot of redundancy, as there can only ever be one package version per Python environment.

In order to avoid having to touch all `get_state` functions to add the package version, it is instead added generically by the dispatch wrapper function.

One wart of this PR is that the list of stdlib modules is hard-coded. There is a [method](https://docs.python.org/3/library/sys.html#sys.stdlib_module_names) to get them in Python 3.10 but not earlier. Thus, it could be possible that the list is not exactly correct for other Python versions. Moreover, it will probably lead to wrong results if the package name is shadowed (say, someone pip installs a package with the name "collections").

### CODE REVIEW

**Comment by adrinjalali** [comment]
I guess a question is, should we care about those versions or not. For example, sklearn itself handles the issue:

https://github.com/scikit-learn/scikit-learn/blob/53acd0fe52cb5d8c6f5a86a1fc1352809240b68d/sklearn/base.py#L265-L294

And that would be the same as pickle, which doesn't store versions, and if a library cares about it, they need to handle it themself.

WDYT?

**Comment by BenjaminBossan** [comment]
Yes, I saw that sklearn already saves the version. My reasoning was that if we have that information (for all packages) right from the start, we may use it later, e.g. to make backwards compatible changes (i.e. loading an old skops save file with a new skops version). This day may never come, but if we don't have it, we shut ourselves out of that option.

**Comment by adrinjalali** [comment]
I'm in favor of having skops version there, I was only wondering about the other underlying packages. Otherwise the skops version makes sense.

**Comment by BenjaminBossan** [comment]
> I'm in favor of having skops version there, I was only wondering about the other underlying packages. Otherwise the skops version makes sense.

I'm open to the suggestion. Just one case where it might hurt: Let's assume that numpy makes a change that is backwards breaking for models saved with skops. If we don't have the numpy version, we could not write backwards compatible code to load the old skops models with new numpy, right?

**Comment by adrinjalali** [comment]
What I don't necessarily want to do, is to do more than pickle. If numpy breaks things, it should handle it for pickle as well, in which case it'd be handled here most probably as well.

We also have our dependencies with their versions in our `config.json`, and that can handle this case on top of potential numpy internals.

So I'd say for this `save/load`, we only save skops version, and not the sub-packages, WDYT?

**Comment by BenjaminBossan** [comment]
Okay, I'll remove the versions except for skops.

> We also have our dependencies with their versions in our `config.json`, and that can handle this case on top of potential numpy internals.

I think `save/load` should be independent of `config.json`.

**Comment by BenjaminBossan** [comment]
@adrinjalali I removed the version from meta info, please review again.

**Review by adrinjalali — APPROVED** [review]

**Comment by adrinjalali** [comment]
I thought you also wanted to refactor a bit and have only two keys on the root level: `metainfo` and `content`, I don't have a strong preference there. Merging this one since it's a nice addition, that refactoring can be done separately.

**Comment by BenjaminBossan** [comment]
> I thought you also wanted to refactor a bit and have only two keys on the root level: `metainfo` and `content`

Oh, I thought you said you did not want that, so I kept the structure flat.

**Comment by adrinjalali** [comment]
I meant to say I'm not sure how it would work, sorry, didn't mean I don't want it. I'm happy for us to see how it'd look like. I think it was a good idea.

**Pull request merged**
